spring:
  profiles:
    active:
    - test

---

spring:
  config:
    activate:
      on-profile: test
name: test-YAML
environment: testing
enabled: false

server:
  port: 8081

matrix: "{{0, 3.25, 7.3}, {3.25, 0, 5.5},{7.3, 5.5, 0}}"

stops:
  Stop1: 0
  Stop2: 1
  Stop3: 2

---

spring:
  config:
    activate:
      on-profile: dev
name: ${DEV_NAME:dev-YAML}
environment: development
enabled: true
