spring:
  profiles:
    active:
    - test

---

spring:
  config:
    activate:
      on-profile: test

server:
  port: 8081

stops:
  Stop1,Stop1: 0
  Stop1,Stop2: 3.25
  Stop1,Stop3: 7.3
  Stop2,Stop1: 3.25
  Stop2,Stop2: 0
  Stop2,Stop3: 5.5
  Stop3,Stop1: 7.3
  Stop3,Stop2: 5.5
  Stop3,Stop3: 0

---

spring:
  config:
    activate:
      on-profile: dev
stops:
  Stop1Stop1: 0